.PHONY: page-build
page-build:
	make -C .. page-build

.PHONY: page-test
page-test: page-build
	open ../_build/default/_doc/_html/Spring-2024/index.html

.PHONY: page-update
page-update:
	make -C .. page-update
