.PHONY: page-build
page-build:
	cp ../../cs320-spring-2025-dev/stdlib320/lib/stdlib320.mli .
	make -C .. page-build

.PHONY: page-test
page-test:
	cp ../../cs320-spring-2025-dev/stdlib320/lib/stdlib320.mli .
	make -C .. page-test
	open ../_build/default/_doc/_html/Spring-2025/lab10.html

.PHONY: page-update
page-update:
	make -C .. page-update
